config/routes.rb
Alpha::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}

    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(
      :name, :email, :password, :password_confirmation, :current_password,
      :address1, :address2, :number, :zipcode, :cpf, :corporate_name, :trade_name, :cnpj, :profile
    )}
  end

  def after_sign_up_path_for(resource)
    edit_user_registration_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/views/home/index.html.slim
.container
  .row
    .col-sm-6.col-sm-offset-4 Oi

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Entrar', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Minha conta', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Cadastre-se', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? &&  can?(:view, User) %>
  <li><%= link_to 'Usuários', users_path %></li>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Alpha'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Alpha'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/users/_user.html.slim
.modal id="role-options-#{user.id}" style=("display: none;") 
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      a.close data-dismiss="modal"  ×
      h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      a.btn data-dismiss="modal" href="#"  Close

app/views/users/index.html.slim
h3 Users
.span8
  table.table.table-condensed
    thead
      tr
        th Username
        th Email
        th Registered
        th Role
        th
        th
    tbody
      - @users.each do |user|
        tr
          td= link_to user.name, user
          td= user.email
          td= user.created_at.to_date
          td= user.roles.first.name.titleize unless user.roles.first.nil?
          td
            a.btn.btn-mini data-toggle="modal" href="#role-options-#{user.id}" type="button"  Change role
            = render user
          td= link_to("Delete user", user_path(user), :data =>   confirm=("Are you sure?" ) , :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.slim
h3 User
p
  | User: #{@user.name}
p
  | Email: #{@user.email if @user.email}
= link_to 'Edit account', edit_user_path